### ISSUE TITLE
[FEAT] Pretty print board

### ISSUE THREAD

**Issue by jesse-wei** [jyou106/WordHunt#6]
Remove commas, quotation marks, brackets.

Board currently printed like

```text
[['C', 'L', 'M', 'W'],
 ['N', 'U', 'K', 'T'],
 ['J', 'N', 'F', 'Z'],
 ['C', 'P', 'I', 'C']]
```

Would prefer something like

```text
C L M W
N U K T
J N F Z
C P I C
```

or with indices:

```text
    0 1 2 3
    - - - -
0 | C L M W
1 | N U K T
2 | J N F Z
3 | C P I C
```

Preferably, allow the user to choose whether to display indices or not with a command-line option.

**Comment by jyou106** [comment]
Fixed by 6d814e0
